### ISSUE TITLE
Vim: List used plugins

### ISSUE THREAD

**Issue by sjakobi** [rainbyte/haskell-ide-chart#1]
The vim row doesn't reveal which plugins are used to get linting etc.

**Comment by rainbyte** [comment]
Thanks for the report... Which items are missing exactly?

Lint is visible via tooltip, if you bring your mouse pointer closer to it.
Also, this is the provided [**link**](https://github.com/vim-syntastic/syntastic "syntastic").

Maybe a browser related issue (?)

**Comment by sjakobi** [comment]
Gosh, I totally missed the tooltips and links. Sorry!
