### ISSUE TITLE
Link to the website in the github repo description

### ISSUE THREAD

**Issue by chris-martin** [rainbyte/haskell-ide-chart#13]
I only just now noticed this was also a jekyll site :)

Please add a link to https://rainbyte.github.io/haskell-ide-chart/ in the repo description to make this discoverable!

**Comment by rainbyte** [comment]
This was supposed to be done later, when issue #6 is solved

**Comment by rainbyte** [comment]
Now I noticed that repo and jekyll site have different font as well... I will have too solve this soon, to have a single font which does not make links invisible.

**Comment by rainbyte** [comment]
I have added the link, even if I couldn't change the styles yet, so I will close this issue.
