### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chris-martin** [rainbyte/haskell-ide-chart#14]
Would you mind adding a license to this repo?

**Comment by rainbyte** [comment]
Do you have some license in mind? It is not code, so I don't know which one is convenient.

**Comment by chris-martin** [comment]
Hm, I just found [choosealicense.com](https://choosealicense.com/non-software/) which seems handy.

**Comment by rainbyte** [comment]
Also read that link, I think CC-BY-4.0 or GPLv3 could be applied

**Comment by chris-martin** [comment]
I'm a public domain fan myself, but you follow your heart :)
