### ISSUE TITLE
add REPL/GHCi supported

### ISSUE THREAD

**Issue by CarstenKoenig** [rainbyte/haskell-ide-chart#15]
don't know you but for me this is a big deal - take Intero/Emacs for example: it's easy to load/reload the current file, switch between the buffers, clear the GHCi buffer and you have autocompletion / syntax highlighting support in the GHCi buffer

AFAIK in vs.code / Haskero you have neither - which is a big showstopper for me

**Comment by rainbyte** [comment]
Thanks for the report, REPL integration is a very important feature. I'll add it today after returning home.

So, emacs + intero support this, but vscode + haskero does not. Do you know about other combinations?

**Comment by CarstenKoenig** [comment]
not from first hand experience but based on the descriptions:

so I cannot say anything about the quality (sorry)

- atom-haskell has it listed as alpha
- cannot find anything on intellij-haskforce
- cannot find anything on intellij-haskell
- I think Leksah has it
- vscode/haskelly apparently has it too
- Vim has it too
- I think you can get it working in Sublime with [SublimeREPL](https://github.com/wuub/SublimeREPL) too

I hope this helps you out a bit

**Comment by rainbyte** [comment]
Well, I have updated the table. Feel free to leave any comment.

If is it of your liking, I will close the issue.

**Comment by CarstenKoenig** [comment]
of course - thanks
