### ISSUE TITLE
Haskell for Mac / Haskell.app missing

### ISSUE THREAD

**Issue by rocketnik** [rainbyte/haskell-ide-chart#29]
The followwing Mac-only IDE is missing:
http://haskellformac.com
https://apps.apple.com/de/app/haskell-development-platform/id841285201?l=en&mt=12

**Comment by rainbyte** [comment]
I have added it to the list, but I don't have a Mac, so I cannot evaluate the score.
Feel free to make a PR with the scores if you tested some of its features.
